services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    #    volumes:
    #      - postgresdata:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
